(function(){
'use strict';
const STORAGE_KEY='wanderbeasts_v1';
const TAIPEI={lat:25.0330,lng:121.5654};
const GRID=0.0025,SPAWN_WINDOW_MS=3*60*1000,SPAWN_RADIUS=0.004,CATCH_RANGE=0.0018;
const ARENA_COUNT=10,MAX_PARTY=3,MAX_BALLS=20,MAX_BERRIES=8,BALL_REFILL_MS=75*1000;
const CATCH_BASE={common:0.72,uncommon:0.52,rare:0.34,epic:0.18};
const RARITY_WEIGHT={common:50,uncommon:30,rare:15,epic:5};
const RARITY_LABEL={common:'常見',uncommon:'少見',rare:'稀有',epic:'傳說'};
const TYPE_LABEL={wood:'木',flame:'焰',tide:'潮',stone:'岩',gale:'嵐',spark:'雷',mist:'霧',bloom:'卉'};
const TYPE_CLASS={wood:'t-wood',flame:'t-flame',tide:'t-tide',stone:'t-stone',gale:'t-gale',spark:'t-spark',mist:'t-mist',bloom:'t-bloom'};
const BESTIARY=[
{id:'mossfox',name:'苔狐',emoji:'🦊',type:'wood',rarity:'common',baseAtk:12,baseHp:40,desc:'棲息於公園綠地的靈狐。'},
{id:'pebbleshell',name:'卵石螺',emoji:'🐚',type:'stone',rarity:'common',baseAtk:10,baseHp:48,desc:'背甲如河卵石。'},
{id:'lanternmoth',name:'燈蛾仔',emoji:'🦋',type:'mist',rarity:'common',baseAtk:11,baseHp:36,desc:'夜間會發出微光。'},
{id:'rivertad',name:'溪蛹',emoji:'🐸',type:'tide',rarity:'common',baseAtk:13,baseHp:38,desc:'從水溝與溪流現身。'},
{id:'sparkbean',name:'電豆',emoji:'⚡',type:'spark',rarity:'uncommon',baseAtk:16,baseHp:34,desc:'觸摸會微微發麻。'},
{id:'breezehare',name:'風兔',emoji:'🐇',type:'gale',rarity:'uncommon',baseAtk:15,baseHp:42,desc:'能乘街巷氣流疾奔。'},
{id:'cindercat',name:'燼貓',emoji:'🐈',type:'flame',rarity:'uncommon',baseAtk:17,baseHp:40,desc:'尾尖常燃著餘燼。'},
{id:'bloomling',name:'花芽精',emoji:'🌸',type:'bloom',rarity:'uncommon',baseAtk:14,baseHp:44,desc:'頭頂開著小花。'},
{id:'stoneturtle',name:'岩盾龜',emoji:'🐢',type:'stone',rarity:'rare',baseAtk:14,baseHp:70,desc:'殼紋像老廟石階。'},
{id:'cloudfish',name:'雲鯉',emoji:'🐟',type:'mist',rarity:'rare',baseAtk:18,baseHp:46,desc:'能在薄霧中游泳。'},
{id:'thunderraven',name:'雷鴉',emoji:'🦅',type:'spark',rarity:'rare',baseAtk:22,baseHp:48,desc:'翼尖帶靜電。'},
{id:'jadeox',name:'翠玉牛',emoji:'🐂',type:'wood',rarity:'rare',baseAtk:20,baseHp:62,desc:'角如翠玉。'},
{id:'tidedragon',name:'汐蛟',emoji:'🐉',type:'tide',rarity:'epic',baseAtk:28,baseHp:72,desc:'與潮汐同起落。'},
{id:'solarphoenix',name:'曦鳳',emoji:'🔥',type:'flame',rarity:'epic',baseAtk:30,baseHp:68,desc:'日出時分偶現。'},
{id:'stormkirin',name:'嵐麒',emoji:'🦄',type:'gale',rarity:'epic',baseAtk:26,baseHp:74,desc:'乘風暴而行。'},
{id:'moonlotus',name:'月蓮姬',emoji:'🌙',type:'bloom',rarity:'epic',baseAtk:24,baseHp:66,desc:'月圓之夜綿放。'}
];
const SPECIES=Object.fromEntries(BESTIARY.map(s=>[s.id,s]));
const ARENA_NAMES=['青石靈壇','風廊據點','苔庭靈壇','曦光據點','汐音靈壇','雷鳴據點','霧港靈壇','翠巒據點','星階靈壇','琥珀據點'];
let state={demo:false,pos:{...TAIPEI},collection:{},partyIds:[],instances:{},caughtSpawnKeys:{},balls:15,berries:5,lastBallRefill:Date.now()};
let map,playerMarker,spawnLayer,arenaLayer,spawns=[],arenas=[],catchAnim=null,battle=null,throwDrag=null;
function toast(msg,ms){const el=document.getElementById('toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.add('hidden'),ms||2800);}
function hash32(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
function mulberry32(a){return function(){let t=a+=0x6d2b79f5;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function uuid(){return 'c_'+Math.random().toString(36).slice(2,10)+Date.now().toString(36).slice(-4);}
function distDeg(a,b){const dlat=a.lat-b.lat,dlng=a.lng-b.lng;return Math.sqrt(dlat*dlat+dlng*dlng);}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return;const data=JSON.parse(raw);state.collection=data.collection||{};state.instances=data.instances||{};state.partyIds=(data.partyIds||[]).filter(id=>state.instances[id]);state.caughtSpawnKeys=data.caughtSpawnKeys||{};state.balls=typeof data.balls==='number'?data.balls:15;state.berries=typeof data.berries==='number'?data.berries:5;state.lastBallRefill=data.lastBallRefill||Date.now();}catch(e){}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({collection:state.collection,instances:state.instances,partyIds:state.partyIds,caughtSpawnKeys:state.caughtSpawnKeys,balls:state.balls,berries:state.berries,lastBallRefill:state.lastBallRefill,savedAt:Date.now()}));updateCollectionCount();updateInventoryUI();}
function refillInventory(){const now=Date.now();const gained=Math.floor((now-state.lastBallRefill)/BALL_REFILL_MS);if(gained>0){state.balls=Math.min(MAX_BALLS,state.balls+gained);state.berries=Math.min(MAX_BERRIES,state.berries+Math.floor(gained/2));state.lastBallRefill+=gained*BALL_REFILL_MS;save();}}
function updateInventoryUI(){const b1=document.getElementById('ball-count');const b2=document.getElementById('ball-count-catch');const br=document.getElementById('berry-count');if(b1)b1.textContent=String(state.balls);if(b2)b2.textContent=String(state.balls);if(br)br.textContent=String(state.berries);}
function timeWindow(){return Math.floor(Date.now()/SPAWN_WINDOW_MS);}
function updateRefreshEta(){const el=document.getElementById('refresh-eta');if(!el)return;const ms=Math.max(0,(timeWindow()+1)*SPAWN_WINDOW_MS-Date.now());const s=Math.ceil(ms/1000);el.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');}
function updateCollectionCount(){document.getElementById('collection-count').textContent=String(Object.keys(state.collection).length);}
function pickWeighted(rng){const total=Object.values(RARITY_WEIGHT).reduce((a,b)=>a+b,0);let r=rng()*total,rarity='common';for(const [k,w] of Object.entries(RARITY_WEIGHT)){r-=w;if(r<=0){rarity=k;break;}}const pool=BESTIARY.filter(s=>s.rarity===rarity);return pool[Math.floor(rng()*pool.length)];}
function makeInstance(speciesId,level){const s=SPECIES[speciesId];const lv=level||1+Math.floor(Math.random()*3);const maxHp=Math.round(s.baseHp+(lv-1)*6);const atk=Math.round(s.baseAtk+(lv-1)*2);const id=uuid();const inst={id,speciesId,level:lv,hp:maxHp,maxHp,atk,xp:0};state.instances[id]=inst;if(!state.collection[speciesId])state.collection[speciesId]={count:0,bestLevel:0};state.collection[speciesId].count+=1;state.collection[speciesId].bestLevel=Math.max(state.collection[speciesId].bestLevel,lv);if(state.partyIds.length<MAX_PARTY)state.partyIds.push(id);return inst;}
function generateSpawns(center){const tw=timeWindow();const prefix=tw+':';Object.keys(state.caughtSpawnKeys).forEach(k=>{if(!k.startsWith(prefix)&&!k.startsWith((tw-1)+':'))delete state.caughtSpawnKeys[k];});const gx0=Math.floor(center.lat/GRID),gy0=Math.floor(center.lng/GRID);const list=[];for(let dx=-3;dx<=3;dx++){for(let dy=-3;dy<=3;dy++){const gx=gx0+dx,gy=gy0+dy,key=tw+':'+gx+':'+gy;const rng=mulberry32(hash32(key+'|wb'));const n=Math.floor(rng()*2.4);for(let i=0;i<n;i++){const spawnKey=key+':'+i;if(state.caughtSpawnKeys[spawnKey])continue;const lat=(gx+rng())*GRID,lng=(gy+rng())*GRID;if(distDeg({lat,lng},center)>SPAWN_RADIUS*1.6)continue;const species=pickWeighted(rng);list.push({spawnKey,lat,lng,speciesId:species.id,level:1+Math.floor(rng()*5)});}}}return list;}
function generateArenas(center){const seed=hash32('arena|'+Math.floor(center.lat/0.02)+'|'+Math.floor(center.lng/0.02));const rng=mulberry32(seed);const list=[];for(let i=0;i<ARENA_COUNT;i++){const angle=rng()*Math.PI*2,dist=0.0012+rng()*0.0045;const lat=center.lat+Math.cos(angle)*dist,lng=center.lng+Math.sin(angle)*dist*1.1;const gRng=mulberry32(hash32('g|'+seed+'|'+i));const rarityRoll=gRng();let rarity='uncommon';if(rarityRoll>0.85)rarity='epic';else if(rarityRoll>0.55)rarity='rare';const pool=BESTIARY.filter(s=>s.rarity===rarity);const guardian=pool[Math.floor(gRng()*pool.length)];const gLevel=4+Math.floor(gRng()*6);list.push({id:'arena_'+i,name:ARENA_NAMES[i%ARENA_NAMES.length],lat,lng,guardians:[{speciesId:guardian.id,level:gLevel},{speciesId:pickWeighted(gRng).id,level:gLevel-1},{speciesId:pickWeighted(gRng).id,level:Math.max(2,gLevel-2)}]});}return list;}
function initMap(){map=L.map('map',{zoomControl:false,attributionControl:true}).setView([state.pos.lat,state.pos.lng],16);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OSM'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);spawnLayer=L.layerGroup().addTo(map);arenaLayer=L.layerGroup().addTo(map);playerMarker=L.marker([state.pos.lat,state.pos.lng],{icon:L.divIcon({className:'',html:'<div class="wb-player"></div>',iconSize:[28,28],iconAnchor:[14,14]}),zIndexOffset:1000}).addTo(map);}
function refreshMarkers(){spawnLayer.clearLayers();arenaLayer.clearLayers();spawns=generateSpawns(state.pos);spawns.forEach(sp=>{const s=SPECIES[sp.speciesId];const m=L.marker([sp.lat,sp.lng],{icon:L.divIcon({className:'',html:'<div class="wb-marker '+s.rarity+'">'+s.emoji+'</div>',iconSize:[36,36],iconAnchor:[18,18]})});m.on('click',()=>onSpawnTap(sp));spawnLayer.addLayer(m);});arenas=generateArenas(state.pos);arenas.forEach(ar=>{const m=L.marker([ar.lat,ar.lng],{icon:L.divIcon({className:'',html:'<div class="wb-marker arena">🏯</div>',iconSize:[40,40],iconAnchor:[20,20]})});m.on('click',()=>openArena(ar));arenaLayer.addLayer(m);});}
function setPlayerPos(lat,lng,recenter){state.pos={lat,lng};if(playerMarker)playerMarker.setLatLng([lat,lng]);if(recenter&&map)map.setView([lat,lng],map.getZoom());refreshMarkers();}
function startGPS(){const btn=document.getElementById('btn-gps');if(!navigator.geolocation){enterDemo('裝置不支援定位');return;}btn.textContent='📍 定位中…';navigator.geolocation.getCurrentPosition(pos=>{state.demo=false;btn.textContent='📍 GPS';btn.classList.add('live');btn.classList.remove('demo');setPlayerPos(pos.coords.latitude,pos.coords.longitude,true);toast('定位成功！附近靈獸已刷新');navigator.geolocation.watchPosition(p=>setPlayerPos(p.coords.latitude,p.coords.longitude,false),()=>{},{enableHighAccuracy:true,maximumAge:5000,timeout:15000});},err=>enterDemo(err&&err.message?err.message:'定位被拒絕'),{enableHighAccuracy:true,timeout:12000,maximumAge:0});}
function enterDemo(reason){state.demo=true;const btn=document.getElementById('btn-gps');btn.textContent='📍 示範模式';btn.classList.add('demo');btn.classList.remove('live');setPlayerPos(TAIPEI.lat,TAIPEI.lng,true);toast('示範模式：台北（'+(reason||'無定位')+'）',3500);}
function onSpawnTap(sp){if(!state.demo&&distDeg(state.pos,sp)>CATCH_RANGE){toast('再靠近一點才能接觸這隻靈獸');return;}openEncounter(sp);}
function openEncounter(sp){refillInventory();const s=SPECIES[sp.speciesId];const beast=document.getElementById('enc-creature');beast.className='creature-live '+TYPE_CLASS[s.type];beast.textContent=s.emoji;document.getElementById('enc-name').textContent=s.name;document.getElementById('enc-meta').innerHTML='<span class="badge r-'+s.rarity+'">'+RARITY_LABEL[s.rarity]+'</span><span class="badge">'+TYPE_LABEL[s.type]+'屬</span> Lv.'+sp.level+'<br>'+s.desc;document.getElementById('catch-area').classList.remove('hidden');document.getElementById('catch-result').classList.add('hidden');document.getElementById('ball-fx').className='hidden';document.getElementById('throw-ball').classList.toggle('disabled',state.balls<=0);updateInventoryUI();catchAnim={spawn:sp,calmed:false,busy:false};document.getElementById('modal-encounter').classList.remove('hidden');}
function useBerry(){if(!catchAnim||catchAnim.busy)return;if(state.berries<=0){toast('沒有靈餌了');return;}state.berries-=1;catchAnim.calmed=true;document.getElementById('enc-creature').classList.add('calmed');save();toast('靈獸吃了靈餌，動作變慢了');}
function startThrow(e){if(!catchAnim||catchAnim.busy)return;if(state.balls<=0){toast('靈球用完了');return;}const t=e.touches?e.touches[0]:e;throwDrag={x:t.clientX,y:t.clientY,t:Date.now()};e.preventDefault();}
function moveThrow(e){if(!throwDrag)return;const t=e.touches?e.touches[0]:e;throwDrag.cx=t.clientX;throwDrag.cy=t.clientY;}
function endThrow(e){if(!throwDrag||!catchAnim){throwDrag=null;return;}const t=(e.changedTouches&&e.changedTouches[0])||e;const x=(t&&t.clientX!=null)?t.clientX:throwDrag.cx;const y=(t&&t.clientY!=null)?t.clientY:throwDrag.cy;const dx=x-throwDrag.x,dy=throwDrag.y-y;throwDrag=null;if(dy<28){toast('往上甩出靈球');return;}launchBall(Math.min(1.2,dy/220),1-Math.min(1,Math.abs(dx)/140),dx);}
function launchBall(power,aim,dx){catchAnim.busy=true;state.balls=Math.max(0,state.balls-1);save();const beast=document.getElementById('enc-creature');const fx=document.getElementById('ball-fx');fx.textContent='⚪';fx.className='';fx.style.transition='none';fx.style.transform='translate('+(dx*0.12)+'px,140px) scale(1)';requestAnimationFrame(function(){fx.style.transition='transform 0.45s cubic-bezier(.2,.7,.2,1)';const missOff=(1-aim)*70*(dx>=0?1:-1);fx.style.transform='translate('+missOff+'px,'+(power>0.55?-8:40)+'px) scale(0.9)';});setTimeout(function(){if(!(power>0.42&&aim>0.35)){fx.classList.add('hidden');catchAnim.busy=false;toast('沒打中，再丟一次');document.getElementById('throw-ball').classList.toggle('disabled',state.balls<=0);return;}beast.classList.add('hit');resolveCatch(aim,power);},480);}
function resolveCatch(aim,power){const sp=catchAnim.spawn,s=SPECIES[sp.speciesId];let rate=(CATCH_BASE[s.rarity]||0.5)*(0.55+aim*0.55)*(0.85+Math.min(0.25,power*0.2));if(catchAnim.calmed)rate+=0.22;rate=Math.min(0.92,rate);const fx=document.getElementById('ball-fx');fx.classList.add('shake');setTimeout(function(){const success=Math.random()<rate;const msg=document.getElementById('catch-msg');document.getElementById('catch-area').classList.add('hidden');document.getElementById('catch-result').classList.remove('hidden');if(success){fx.classList.remove('shake');fx.classList.add('capture');const inst=makeInstance(sp.speciesId,sp.level);state.caughtSpawnKeys[sp.spawnKey]=true;save();msg.innerHTML='<strong style="color:var(--accent)">收服成功！</strong><br>獲得 '+s.emoji+' '+s.name+' Lv.'+inst.level;toast('收服了 '+s.name+'！');refreshMarkers();}else{fx.classList.add('hidden');const beast=document.getElementById('enc-creature');beast.classList.remove('hit');beast.classList.add('flee');state.caughtSpawnKeys[sp.spawnKey]=true;save();msg.innerHTML='<strong style="color:var(--danger)">掙脫逃走了…</strong><br>'+s.name+' 消失在風中。';refreshMarkers();}catchAnim=null;},1400);}
function closeEncounter(){document.getElementById('modal-encounter').classList.add('hidden');throwDrag=null;catchAnim=null;}
function openArena(ar){document.getElementById('arena-title').textContent=ar.name;document.getElementById('arena-desc').textContent='守護靈：'+ar.guardians.map(g=>SPECIES[g.speciesId].emoji+SPECIES[g.speciesId].name+' Lv.'+g.level).join(' · ');document.getElementById('arena-setup').classList.remove('hidden');document.getElementById('arena-battle').classList.add('hidden');document.getElementById('arena-result').classList.add('hidden');battle={arena:ar,pick:[...state.partyIds].slice(0,MAX_PARTY)};renderArenaPartyPick();document.getElementById('btn-start-battle').disabled=!(battle.pick.length>0);document.getElementById('modal-arena').classList.remove('hidden');}
function renderArenaPartyPick(){const box=document.getElementById('arena-party-pick');const ids=Object.keys(state.instances);if(!ids.length){box.innerHTML='<p class="hint">尚未收服任何靈獸</p>';return;}box.innerHTML=ids.map(id=>{const inst=state.instances[id],s=SPECIES[inst.speciesId],sel=(battle&&battle.pick.includes(id))?' selected':'';return '<div class="creature-card'+sel+'" data-pick="'+id+'"><div class="creature-avatar '+TYPE_CLASS[s.type]+'">'+s.emoji+'</div><div class="creature-info"><h4>'+s.name+'</h4><p class="meta">Lv.'+inst.level+'</p></div></div>';}).join('');box.querySelectorAll('[data-pick]').forEach(el=>{el.addEventListener('click',()=>{const id=el.getAttribute('data-pick');const idx=battle.pick.indexOf(id);if(idx>=0)battle.pick.splice(idx,1);else if(battle.pick.length<MAX_PARTY)battle.pick.push(id);else toast('最多選 3 隻');renderArenaPartyPick();document.getElementById('btn-start-battle').disabled=!(battle.pick.length>0);});});}
function startBattle(){battle.allies=battle.pick.map(id=>{const inst=state.instances[id],s=SPECIES[inst.speciesId];return Object.assign({},inst,{hp:inst.maxHp,name:s.name,emoji:s.emoji,type:s.type});});battle.enemies=battle.arena.guardians.map(g=>{const s=SPECIES[g.speciesId];const maxHp=Math.round(s.baseHp+(g.level-1)*6);const atk=Math.round(s.baseAtk+(g.level-1)*2);return {speciesId:g.speciesId,level:g.level,hp:maxHp,maxHp,atk,name:s.name,emoji:s.emoji,type:s.type};});battle.ai=0;battle.ei=0;battle.busy=false;document.getElementById('arena-setup').classList.add('hidden');document.getElementById('arena-battle').classList.remove('hidden');document.getElementById('arena-result').classList.add('hidden');syncBattleUI('挑戰開始！');}
function syncBattleUI(log){const a=battle.allies[battle.ai],e=battle.enemies[battle.ei];document.getElementById('ally-sprite').className='creature-hero sm '+TYPE_CLASS[a.type];document.getElementById('ally-sprite').textContent=a.emoji;document.getElementById('enemy-sprite').className='creature-hero sm '+TYPE_CLASS[e.type];document.getElementById('enemy-sprite').textContent=e.emoji;document.getElementById('ally-label').textContent=a.name+' Lv.'+a.level;document.getElementById('enemy-label').textContent=e.name+' Lv.'+e.level;document.getElementById('ally-hp').style.width=Math.max(0,(a.hp/a.maxHp)*100)+'%';document.getElementById('enemy-hp').style.width=Math.max(0,(e.hp/e.maxHp)*100)+'%';if(log)document.getElementById('battle-log').textContent=log;}
function typeBonus(atkType,defType){const strong={wood:'tide',flame:'wood',tide:'flame',stone:'spark',gale:'bloom',spark:'tide',mist:'flame',bloom:'stone'};if(strong[atkType]===defType)return 1.35;if(strong[defType]===atkType)return 0.75;return 1;}
function doAttack(skill){if(!battle||battle.busy)return;const a=battle.allies[battle.ai],e=battle.enemies[battle.ei];if(!a||!e||a.hp<=0)return;battle.busy=true;const dmg=Math.max(1,Math.round(a.atk*(skill?1.45:1)*typeBonus(a.type,e.type)*(0.85+Math.random()*0.3)));e.hp=Math.max(0,e.hp-dmg);syncBattleUI(a.name+' 使出'+(skill?'靈技':'攻擊')+'！造成 '+dmg+' 傷害');setTimeout(function(){if(e.hp<=0){battle.ei+=1;if(battle.ei>=battle.enemies.length){endBattle(true);return;}syncBattleUI('下一隻守護靈登場！');battle.busy=false;return;}const edmg=Math.max(1,Math.round(e.atk*typeBonus(e.type,a.type)*(0.85+Math.random()*0.3)));a.hp=Math.max(0,a.hp-edmg);syncBattleUI(e.name+' 反擊！你受到 '+edmg+' 傷害');if(a.hp<=0){battle.ai+=1;if(battle.ai>=battle.allies.length){endBattle(false);return;}syncBattleUI('換上 '+battle.allies[battle.ai].name+'！');}battle.busy=false;},550);}
function swapAlly(){if(!battle||battle.busy)return;const alive=battle.allies.map((c,i)=>({c,i})).filter(x=>x.c.hp>0&&x.i!==battle.ai);if(!alive.length){toast('沒有可換的夥伴');return;}battle.ai=alive[0].i;syncBattleUI('換上 '+battle.allies[battle.ai].name+'！');}
function endBattle(won){battle.busy=true;document.getElementById('arena-battle').classList.add('hidden');document.getElementById('arena-result').classList.remove('hidden');document.getElementById('arena-result-msg').innerHTML=won?'<strong style="color:var(--accent)">挑戰成功！</strong>':'<strong style="color:var(--danger)">挑戰失敗…</strong>';}
function closeArena(){document.getElementById('modal-arena').classList.add('hidden');battle=null;}
function renderParty(){const box=document.getElementById('party-list');const ids=Object.keys(state.instances);if(!ids.length){box.innerHTML='<p class="hint">還沒有靈獸。</p>';return;}box.innerHTML=ids.map(id=>{const inst=state.instances[id],s=SPECIES[inst.speciesId],inParty=state.partyIds.includes(id);return '<div class="creature-card'+(inParty?' selected':'')+'" data-party="'+id+'"><div class="creature-avatar '+TYPE_CLASS[s.type]+'">'+s.emoji+'</div><div class="creature-info"><h4>'+s.name+(inParty?' ★':'')+'</h4><p class="meta">Lv.'+inst.level+'</p></div></div>';}).join('');box.querySelectorAll('[data-party]').forEach(el=>{el.addEventListener('click',()=>{const id=el.getAttribute('data-party');const idx=state.partyIds.indexOf(id);if(idx>=0)state.partyIds.splice(idx,1);else if(state.partyIds.length<MAX_PARTY)state.partyIds.push(id);else toast('隊伍最多 3 隻');save();renderParty();});});}
function renderBestiary(){document.getElementById('bestiary-list').innerHTML=BESTIARY.map(s=>{const col=state.collection[s.id],locked=!col;return '<div class="creature-card'+(locked?' locked':'')+'"><div class="creature-avatar '+TYPE_CLASS[s.type]+'">'+(locked?'❓':s.emoji)+'</div><div class="creature-info"><h4>'+(locked?'？？？':s.name)+'</h4><p class="meta"><span class="badge r-'+s.rarity+'">'+RARITY_LABEL[s.rarity]+'</span> '+(locked?'尚未發現':'×'+col.count)+'</p></div></div>';}).join('');}
function showPanel(name){['party','bestiary','help'].forEach(p=>document.getElementById('panel-'+p).classList.toggle('hidden',p!==name));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.panel===(name||'map')));if(name==='party')renderParty();if(name==='bestiary')renderBestiary();}
function bindUI(){document.getElementById('btn-gps').addEventListener('click',()=>{if(state.demo)startGPS();else toast('GPS 運作中');});document.getElementById('btn-collection').addEventListener('click',()=>showPanel('bestiary'));document.getElementById('btn-balls').addEventListener('click',()=>{refillInventory();toast('靈球 '+state.balls+' / 靈餌 '+state.berries);});document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{const p=btn.dataset.panel;if(p==='map')showPanel(null);else showPanel(p);}));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>showPanel(null)));document.getElementById('btn-berry').addEventListener('click',useBerry);document.getElementById('btn-enc-done').addEventListener('click',closeEncounter);document.getElementById('enc-close').addEventListener('click',closeEncounter);const ball=document.getElementById('throw-ball');ball.addEventListener('pointerdown',startThrow);window.addEventListener('pointermove',moveThrow);window.addEventListener('pointerup',endThrow);document.getElementById('btn-start-battle').addEventListener('click',startBattle);document.getElementById('btn-atk').addEventListener('click',()=>doAttack(false));document.getElementById('btn-skill').addEventListener('click',()=>doAttack(true));document.getElementById('btn-swap').addEventListener('click',swapAlly);document.getElementById('btn-arena-done').addEventListener('click',closeArena);document.getElementById('arena-close').addEventListener('click',closeArena);let lastTw=-1;setInterval(()=>{refillInventory();updateRefreshEta();const tw=timeWindow();if(map&&tw!==lastTw){lastTw=tw;refreshMarkers();if(lastTw>0)toast('附近靈獸刷新了');}},1000);}
function boot(){load();refillInventory();updateCollectionCount();updateInventoryUI();updateRefreshEta();initMap();bindUI();startGPS();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
